spring:
  application:
    name: magic-trade-api
  datasource:
    url: jdbc:postgresql://localhost:5432/mtg_trade_api
    username: postgres
    password: pass123
    driver-class-name: org.postgresql.Driver

  # AGORA SIM ELES ESTÃO DENTRO DE SPRING (2 espaços de recuo)
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

# Logging fica na coluna 1, fora do spring
logging:
  level:
    org.flywaydb: DEBUG
    org.hibernate.SQL: DEBUG